#This actions example is to create a file with text

name: "My action"
description: "Test my action"

inputs:
  message:
    description: "Message file description"
    required: true
    default: "Hello this is this is the default message"
  folder-name:
    description: "Folder name"
    required: true
    default: "folder"
  file-name:
    description: "File name"
    required: true
    default: "file.txt"
runs:
  using: "composite" # composite allow us to group by commons step and call from differents workflows

  steps:
    - name: Hola mundo
      run: |
        mkdir ${{ inputs.folder-name }}
        cd  ${{ inputs.folder-name }}
        echo "${{ inputs.message }}" > ${{ inputs.file-name }}
      shell: bash
