name: "Services composite action"
description: "This action works with services"

runs: 
  using: "composite"

  services:
    mysql:
      image: mysql:5.7
      env:
        MYSQL_ROOT_PASSWORD: example
      ports:
        - 3306:3306
  
  steps:
    - name: Test container
      run: docker --version