#File to create actions

name: "My action"
description: "Test my action"

runs:
  using: "composite" # composite allow us to group by commons step and call from differents workflows
  
  steps:
    - name: Hola mundo
      run: echo "Hola mundo"
      shell: bash