name: Test composite action

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Welcome to github-actions, thanks for type this message :D"
          folder-name: "folder-tst"
          file-name: "file-tst.txt"
      - name: Show file Content
        run: |
            cd folder-tst
            cat file-tst.txt
      - name: Run docker image
        uses: ../.github/actions/docker-action

      