#this action is for lesson 1 from module 3

name: Modulo 3 gituhub actions course
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      MY_VAR: Mí variable de entorno 
    steps:
      - name: Step one
        env:
          STEP_MY_VAR: Nivel step
        run: |
            echo "Valor de variable de entorno a nivel job ${MY_VAR}" echo "Valor de variable de entorno a nivel step ${STEP_MY_VAR}"